sudo: false

language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

script:
  - flake8 --exclude **migrations*,manage.py,**settings.py
  - python manage.py test

#after_success:
#  - codecov