# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_distributedprompt_translated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompt',
            options={},
        ),
    ]
