# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected', models.BooleanField(default=False)),
                ('recorded', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotations.Prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promptrecording',
            name='annotation',
            field=models.TextField(default='XXX'),
            preserve_default=False,
        ),
    ]
