# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 23, 6, 14, 326575)),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 23, 6, 14, 323863)),
        ),
    ]
