# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20171009_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationrecording',
            name='file_url',
            field=models.FileField(upload_to=''),
        ),
    ]
