# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20171005_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtranslation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 23, 7, 47, 455773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='annotationrecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 23, 7, 47, 452373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 23, 7, 47, 446211, tzinfo=utc)),
        ),
    ]
