# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20171005_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationrecording',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='annotationtranslation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
