# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:39
from __future__ import unicode_literals

import annotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20171009_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationrecording',
            name='file_type',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='annotationrecording',
            name='file_url',
            field=models.FileField(upload_to=annotations.models.AnnotationRecording.update_filename),
        ),
    ]
