# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='second_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_language', to='user.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='third_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_language', to='user.Language'),
        ),
    ]
