# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='second_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_language', to='user.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='third_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_language', to='user.Language'),
        ),
    ]
